package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class GUIConsultBalanceController {
	@FXML
	private TextField tfConsultBalance;
	@FXML
	private Button btnConsultBalance;
	@FXML
	private TableView tvShowStudentBalance;
	@FXML
	private TableColumn tvColumnCarnet;
	@FXML
	private TableColumn tvColumnStudent;
	@FXML
	private TableColumn tvColumnReloadDate;
	@FXML
	private TableColumn tvColumnBalance;
	@FXML
	private Button btnReturnToHome;
	@FXML
	private Button btnAddNewStudent;

	// Event Listener on Button[#btnConsultBalance].onAction
	@FXML
	public void consultStudentBalance(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnReturnToHome].onAction
	@FXML
	public void returnHome(ActionEvent event) {
		closeWindows();
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAddNewStudent].onAction
	@FXML
	public void addNewStudent(ActionEvent event) {
		try {
			
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIAddNewStudentForm.fxml"));
			
			Parent root = loader.load();
			Scene scene = new Scene(root);
			//scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); //sino lo configuro se nececita agregar aqui
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			Stage temp = (Stage)btnAddNewStudent.getScene().getWindow();
			temp.close();
		} catch(Exception e) {
			e.printStackTrace();
		}	
	}
	public void closeWindows() {
try {
			
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIMenuHome.fxml"));
			
			Parent root = loader.load();
			Scene scene = new Scene(root);
			//scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm()); sino lo configuro se nececita agregar aqui
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			Stage temp = (Stage)btnReturnToHome.getScene().getWindow();
			temp.close();
		} catch(Exception e) {
			e.printStackTrace();
		}	
	}
}
